apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sykepengedager
  namespace: aap
  labels:
    team: aap
    sub: vedtak
spec:
  image: {{image}}
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafka.pool}}
    streams: true
  replicas:
    cpuThresholdPercentage: 90
    disableAutoScaling: true
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  liveness:
    path: /actuator/live
    initialDelay: 1
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: /actuator/ready
    initialDelay: 1
    periodSeconds: 1
    failureThreshold: 60
  prometheus:
    enabled: true
    path: /actuator/metrics
  env:
    - name: TOGGLE_SETT_OPP_PRODSTREAM
      value: "{{toggle.sett-opp-prod-stream}}"
