kafka:
  pool: nav-dev
  permanent-delete-topics: true
  sykepengedagerInfotrygdSecretName: sykepengedager-infotrygd-dev-e45by45w
  acl:
    dev:
      - team: aap
        application: devtools
        access: readwrite
      - team: aap
        application: aap-kafka-manager
        access: read
      - team: aap
        application: kafka-cli
        access: readwrite
