apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: subscribe-sykepengedager.v1
  namespace: aap
  labels:
    team: aap
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "{{kafka.permanent-delete-topics}}"
    github.url: https://github.com/navikt/aap-sykepengedager
spec:
  pool: {{kafka.pool}}
  config:
    cleanupPolicy: compact
    partitions: 12
  acl:
    - team: aap
      application: sykepengedager
      access: read
    - team: aap
      application: vedtak
      access: write
# TODO: midlertidig fix. bot skal ikke trenge å subscribe her, det er noe i vedtak/sykepengedager som må løses
    - team: aap
      application: bot
      access: write
  {{#each kafka.acl.dev as |dev|}}
    - team: "{{dev.team}}"
      application: "{{dev.application}}"
      access: "{{dev.access}}"
  {{/each}}
